api_platform:
    title: 'ESBV API'
    version: '1.0.0'
    description: 'API pour le site e-commerce ESBV'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        versions: [3]
        swagger_ui_extra_configuration:
            persistAuthorization: true
            docExpansion: 'list'
            filter: true
            operationsSorter: 'alpha'
            tagsSorter: 'alpha'
            deepLinking: true
